:PROPERTIES:
:ID:       91107c6b-aaab-484e-94f3-49d68224e172
:END:
#+title: Yogurt Batch Plan

* Try [[https://www.positivelyprobiotic.com/shop-all-cultures/p/beijing-thermophilic-heirloom-yogurt-starter-culture][Beijing Thermophilic Heirloom Yogurt Starter Culture]]

Beijing yogurt is a drinkable yogurt. Popular in China and Northern Vietnam. Traditionally served in ceramic containers that are usually returned for reuse. It’s equal part sweet and tart. So delicious.

* Try [[https://www.positivelyprobiotic.com/shop-all-cultures/p/balkan-style-heirloom-thermophilic-yogurt-starter-culture][Balkan Thermophilic Heirloom Yogurt Starter Culture]]

Balkan Style is unique like French yogurt as its usually consumed unstirred. It’s creamy yet thick. Holds its shape well on the spoon. Equal parts sweet and tart. Usually set in the vessel you would use to consume the yogurt.

* Try [[https://www.positivelyprobiotic.com/shop-all-cultures/p/san-francisco-sourdough-starter-culture-bread-yeast][San Francisco Sourdough Starter Culture]]

This San Francisco sourdough starter is truly remarkable, boasting a remarkable level of liveliness and activity that brings an extra dimension of authenticity to your baking. When it comes to sourdough bread, the mere mention of San Francisco conjures images of tradition and excellence. The balanced and beautiful nature of this starter further cements its status as a quintessential representation of the art of sourdough craftsmanship.
