:PROPERTIES:
:ID:       004544cc-8e99-4ff8-b41b-05034f60a05a
:ROAM_REFS: @ugareSynCodeLLMGeneration2024
:END:
#+title: SynCode: LLM Generation with Grammar Augmentation - Ugare, Shubham and Suresh, Tarun and Kang, Hangoo and Misailovic, Sasa and Singh, Gagandeep

* Difficulty with current grammar guided generation
** Issues with syntactical accuracy
*Token misalignment*: LLM token do not directly correspond to lexical tokens of a grammar
** Issues with high computational overhead:
- The algorithm should facilitate offline computations that minimize the overhead
during inference.
- It should effectively utilize available hardware resources and offload additional
computations to modern hardware, such as GPUs, to enable parallel computation.
** Issues with generality
- Prior works are restricted to specific LLM decoding schemes
* SynCode Algorithm
** Parsing Partial Output
- Remainder \(r\) denotes the suffix of \(C_{k}\) that may still change its lexical type in subsequent iterations.
- Given a sequence of lexical tokens \(l_{1} , . . . l_{f} \), we use a bottom-up LR parser to compute what types of lexical tokens are acceptable next according to the grammar.
  - Given current remainder \(r\) and token \(t\) in LLM vocabulary, use a DFA to check whether \(r.t\) is acceptable. Pre-compute DFA to check which \(t\) is acceptable in each DFA state
